#!/bin/bash

########################################
# Author: Biprodeep Roy(v!rtu4lGh0st)  #
#                                      # 
# Setup                                #
#                                      #
# Build: WSp0t v1.0                    #
#                                      #
########################################

sudo apt-get install util-linux procps hostapd iproute2 iw haveged dnsmasq iptables;

tar -xvzf create_ap.tar.gz

cd create_ap

sudo make install

cd ..

cp wsp0t /usr/bin
cp wooo /usr/bin

chmod +x wsp0t
chmod +x wooo

echo -e "\033[1;32m         [\033[1;33m+\033[1;32m]Setup completed: Now type in 'sudo wsp0t' to start working! :) \033[0m"
